Revert back to 1.19 because of issues
```
Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"6174fccbb6c0e0d6-IAD","code":"Ef9cc","description":"The cluster could not be updated. The master must be in the deployed state to perform and update.","type":"BadRequest"}
```